### PR TITLE
Use explicit integer division. Closes #123

### LINKED ISSUE #123: Testsuite failure on Debian unstable
Hi Rich,

The Debian CI reports a failure of running the test suite with the installed package on Debian for Python 3 only. It runs fine on Python 2.7. The test logs are available [here](https://ci.debian.net/data/packages/unstable/amd64/p/python-dtcwt/20160206_220843.autopkgtest.log.gz), which includes the list of packages and dependencies used to run the testsuite.

Could you check what is wrong and propose a fix ?

Many thanks.

Ghis

### PR DESCRIPTION
**Pull request by ghisvail**

### CODE REVIEW

**Comment by rjw57** [comment]
Looks good to me.

**Comment by rjw57** [comment]
Merged, thanks.

**Comment by ghisvail** [comment]
You're welcome. Any plans for an update soon?

**Comment by rjw57** [comment]
Fixing the Travis builds at the moment. Then 0.11 will be released with improved OpenCL support.

**Comment by rjw57** [comment]
And 0.11 is now released. Is there a preferred location for me to post new releases in future?

**Comment by ghisvail** [comment]
I am sync'd with the GitHub releases, but your users may expect to find it on `PyPI` and install it via `pip`.

**Comment by rjw57** [comment]
> your users may expect to find it on PyPI and install it via pip.

Like this: https://pypi.python.org/pypi/dtcwt :)

**Comment by ghisvail** [comment]
Yep. Congrats for the release.

**Pull request merged**
